# Generated by Django 4.1 on 2024-01-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='gallery', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
